DjangoSomeSite/agenda/urls.py
from django.urls import path
# from django.views.generic import RedirectView

from . import views


app_name = 'agenda'
urlpatterns = [
    path('', views.list_event, name='index'),
    path('history/', views.list_history, name='history'),
    path('event/<int:event_id>', views.new_event, name='new'),
    path('event/submit/', views.submit_event, name='submit'),
    path('event/delete/<int:event_id>', views.delete_event, name='delete'),
    path('api/', views.list_json),
]

DjangoSomeSite/login/urls.py
from django.urls import path

from . import views


app_name = 'login'
urlpatterns = [
    path('', views.login_user, name='index'),
    path('submit/', views.submit_login, name='submit'),
    path('logout/', views.logout_user, name='logout')
]

DjangoSomeSite/somesite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('agenda/', include('agenda.urls')),
    path('login/', include('login.urls'))
]

DjangoSomeSite/agenda/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class Event(models.Model):
    title = models.CharField(
        max_length=100, verbose_name='Título'
    )
    description = models.TextField(
        blank=True, null=True, verbose_name='Descrição'
    )
    local = models.TextField(
        blank=True, null=True, verbose_name='Local'
    )
    date = models.DateTimeField(
        verbose_name='Data do evento'
    )
    creation_date = models.DateTimeField(
        auto_now=True, verbose_name='Data da criação'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Usuário'
    )

    class Meta:
        db_table = 'evento'

    def __str__(self):
        return self.title

    def get_event_input_date(self):
        return self.date.strftime('%Y-%m-%dT%H:%M')

    def islate(self):
        return self.date < timezone.now()

    def isimminent(self):
        now = timezone.now()
        return now < self.date < now + timedelta(hours=1)

DjangoSomeSite/agenda/views.py
from datetime import datetime, timedelta

from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.http.response import Http404, JsonResponse
from django.utils import timezone

from .models import Event

# Create your views here.


def str_to_aware_time(time: str) -> datetime:
    time = datetime.strptime(time, '%Y-%m-%dT%H:%M')
    return timezone.make_aware(time)


@login_required(login_url='/login/')
def list_event(request):
    user = request.user
    time_now = timezone.now()
    events = Event.objects.filter(
        user=user,
        date__gt=time_now - timedelta(hours=1)
    )
    data = {'events': events}
    return render(request, 'agenda/index.html', data)


@login_required(login_url='/login/')
def list_history(request):
    events = Event.objects.filter(
        user=request.user,
        date__lt=timezone.now() - timedelta(hours=1)
    )
    data = {'events': events}
    return render(request, 'agenda/history.html', data)


@login_required(login_url='/login/')
def new_event(request, event_id):
    data = {}
    if event_id:
        data['event'] = Event.objects.get(id=event_id)
    return render(request, 'agenda/new_event.html', data)


@login_required(login_url='/login/')
def submit_event(request):
    if request.POST:
        title = request.POST.get('title')
        date = str_to_aware_time(request.POST.get('date'))
        description = request.POST.get('description')
        local = request.POST.get('local')
        user = request.user
        event_id = request.POST.get('event_id')
        if event_id:
            Event.objects.filter(id=event_id).update(
                title=title,
                date=date,
                description=description,
                local=local
            )
        else:
            Event.objects.create(
                title=title,
                date=date,
                description=description,
                local=local,
                user=user
            )
    return redirect(reverse('agenda:index'))


@login_required(login_url='/login/')
def delete_event(request, event_id):
    user = request.user
    event = Event.objects.get(id=event_id)
    if user == event.user:
        event.delete()
    else:
        raise Http404()
    return redirect(reverse('agenda:index'))


@login_required(login_url='/login/')
def list_json(request):
    event = Event.objects.filter(
        user=request.user
    ).values('id', 'title', 'date',
             'creation_date', 'description', 'local')
    return JsonResponse(list(event), safe=False)

DjangoSomeSite/agenda/templates/agenda/history.html
{% extends "agenda/model_page.html" %}

{% block content %}
<h2>Histórico</h2>
  <ul>
  {% for event in events %}
    <li>{{ event.title }} - {{ event.date }}</li>
  {% endfor %}
  </ul>
<a href="{% url 'agenda:index' %}"><button type="button">Voltar</button></a>
{% endblock %}

DjangoSomeSite/agenda/templates/agenda/index.html
{% extends "agenda/model_page.html" %}

{% block content %}
    <h2>Agendamentos</h2>
    <ul>
        {% for event in events %}
            <li>
                <div {% if event.islate %} style="color:red" {% endif %}
                     {% if event.isimminent %} style="color:orange" {% endif %}>
                    {{ event.title }} - {{ event.date }} 
                    (<a href="{% url 'agenda:new' event.id %}">Editar</a> /
                    <a href="{% url 'agenda:delete' event.id %}">Excluir</a>)
                </div>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'agenda:new' 0 %}">
        <button type="button">Novo evento</button>
    </a>
    <a href="{% url 'agenda:history' %}">
        <button type="button">Histórico</button>
    </a>
{% endblock %}

DjangoSomeSite/agenda/templates/agenda/model_footer.html
<footer>Desenvolvido por Henrique do Val</footer>

DjangoSomeSite/agenda/templates/agenda/model_header.html
<meta charset="UTF-8">
<title>Agenda</title>
<div align="right">
  <a href="{% url 'login:logout' %}">Logout</a>
</div>
<h1>Agenda</h1>

DjangoSomeSite/agenda/templates/agenda/model_page.html
<!DOCTYPE html>
<html lang="pt_BR">
    <head>
        {% include "agenda/model_header.html" %}
    </head>
    <body>
        {% block content %} {% endblock %}
        {% include "agenda/model_footer.html" %}
    </body>
</html>

DjangoSomeSite/agenda/templates/agenda/new_event.html
{% extends "agenda/model_page.html" %}

{% block content %}
<h2>{% if event.id %}Editar{% else %}Novo{% endif %} evento</h2>

<form action="{% url 'agenda:submit' %}" method="post"> {% csrf_token %}
    <input type="number" name="event_id" value="{{ event.id }}" hidden>

    <label>Título:</label>
    <input type="text" name="title" size=22 value="{{ event.title }}"><br>

    <label>Data:</label>                                           <!--%Y-%m-%dT%H:%M--!>
    <input type="datetime-local" name="date" value="{{ event.date|date:'Y-m-d' }}{{ event.date|time:'\TH:i'}}"><br>
    <label>Descrição:</label><br>
    <textarea name="description" cols="28" rows="5">{{ event.description }}</textarea>
    <br>

    <label>Local:</label>
    <input type="text" name="local" size="22" value="{{ event.local }}">
    <br><br>

    <button type="submit">Salvar</button>
    <a href="{% url 'agenda:index' %}">
        <button type="button">Cancelar</button>
    </a>
</form>
{% endblock %}