DjangoSomeSite/login/urls.py
from django.urls import path

from . import views


app_name = 'login'
urlpatterns = [
    path('', views.login_user, name='index'),
    path('submit/', views.submit_login, name='submit'),
    path('logout/', views.logout_user, name='logout')
]

DjangoSomeSite/somesite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('agenda/', include('agenda.urls')),
    path('login/', include('login.urls'))
]

DjangoSomeSite/login/models.py
from django.db import models

# Create your models here.

DjangoSomeSite/login/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.


def login_user(request):
    return render(request, 'login/index.html')


def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('agenda:index'))
        else:
            messages.error(request, 'Usuário ou senha inválido')
    return redirect('/')


def logout_user(request):
    logout(request)
    return redirect('/')

DjangoSomeSite/login/templates/login/index.html
<!DOCTYPE html>
<html lang="pt_Br">
    <head>
        <title>Agenda</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'stylelogin.css' %}">
    </head>
    <body>
        <section>
            <div class="login">
                <h1>Login</h1>
            </div>

            <div class="usuario">
              <form action="{% url 'login:submit' %}" method="post"> {% csrf_token %}  
                <label>Usuário:</label>
                <input type="text" name="username"><br>
                <label>Senha:</label>
                <input type="password" name="password">
                <button type="submit">Entrar</button>
              </form>
            </div>
            
            <div class="erro">
            {% for message in messages %}
                <strong>Erro: </strong>{{ message }}
            {% endfor %}
            </div>
        </section>
    </body>
</html>